name: Deploy Treinazap-PRD -S3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.21.0
      - name: INSTALL E BUILD
        run: npm install && npm run build
      - name:  LISTAR ARQUIVOS
        run: ls -la build/*     
        env:
           CI: "false"       
            
